# Generated by Django 4.2.7 on 2024-01-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='chat_documents/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chat_photos/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos/'),
        ),
    ]
