# Generated by Django 4.2.7 on 2024-01-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_document_chatmessage_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
